apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sit-cicd-demo
  template:
    metadata:
      labels:
        app: sit-cicd-demo
    spec:
      containers:
        - name: springboot
          image: zasmin/sit-cicd-demo:1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jhooq-springboot
